[[main]]
    identifier = "home"
    name       = "首页"
    url        = "/"

    [main.params]
        icon = "home"

[[main]]
    identifier = "post"
    name       = "博客"
    url        = "/post/"

[[main]]
    identifier = "news"
    name       = "新闻"
    url        = "/news/"

[[main]]
    identifier = "archives"
    name       = "归档"
    url        = "/archives/"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/openlight"

    [social.params]
        icon = "brand-github"
